import React from 'react';
import { useBible } from '../context/BibleContext';
import {
  Home,
  BookOpen,
  Search,
  Bookmark,
  Heart,
  FileText,
  SlidersHorizontal,
  Compass,
  Database,
  History,
  HelpCircle,
  Sparkles,
} from 'lucide-react';

export const Sidebar: React.FC = () => {
  const { currentLanguage, activeTab, setActiveTab, bookmarks, favorites, notes } = useBible();

  interface SidebarLink {
    id: 'home' | 'bible' | 'topics' | 'search' | 'quiz' | 'plans' | 'saved' | 'settings' | 'admin';
    label: string;
    icon: React.ElementType;
    count?: number;
  }

  const links: SidebarLink[] = [
    { id: 'home', label: currentLanguage === 'ta' ? 'முகப்பு' : 'Home', icon: Home },
    { id: 'bible', label: currentLanguage === 'ta' ? 'வேதாகமம்' : 'Books', icon: BookOpen },
    { id: 'topics', label: currentLanguage === 'ta' ? 'வேதாகம தலைப்புகள்' : 'Bible Topics', icon: Sparkles },
    { id: 'search', label: currentLanguage === 'ta' ? 'தேடல்' : 'Search', icon: Search },
    { id: 'quiz', label: currentLanguage === 'ta' ? 'வினாடி வினா' : 'Scripture Quiz', icon: HelpCircle },
    { id: 'plans', label: currentLanguage === 'ta' ? 'வாசிப்புத் திட்டங்கள்' : 'Reading Plans', icon: Compass },
    {
      id: 'saved',
      label: currentLanguage === 'ta' ? 'சேமிக்கப்பட்டவை' : 'Saved Items',
      icon: Bookmark,
      count: bookmarks.length + favorites.length + notes.length,
    },
    { id: 'settings', label: currentLanguage === 'ta' ? 'அமைப்புகள்' : 'Settings', icon: SlidersHorizontal },
    { id: 'admin', label: currentLanguage === 'ta' ? 'தரவு தணிக்கை' : 'Dataset Validator', icon: Database },
  ];

  return (
    <aside className="hidden md:flex flex-col w-56 lg:w-64 bg-[#14161C] border-r border-[#242731] shrink-0 p-4 min-h-[calc(100vh-3.5rem)]">
      <div className="space-y-1">
        {links.map((link) => {
          const Icon = link.icon;
          const isActive =
            activeTab === link.id || (link.id === 'bible' && activeTab === 'reader');

          return (
            <button
              key={link.id}
              onClick={() => setActiveTab(link.id as any)}
              className={`w-full flex items-center justify-between px-3.5 py-2.5 rounded-xl text-xs font-medium transition-all ${
                isActive
                  ? 'bg-[#D4AF37]/15 text-[#D4AF37] font-semibold border border-[#D4AF37]/30 shadow-xs'
                  : 'text-[#989286] hover:text-[#EDE8DF] hover:bg-[#1B1E26] border border-transparent'
              }`}
            >
              <div className="flex items-center gap-3">
                <Icon className="w-4 h-4 shrink-0" />
                <span>{link.label}</span>
              </div>
              {link.count !== undefined && link.count > 0 && (
                <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-[#202430] text-[#A9A397] font-mono">
                  {link.count}
                </span>
              )}
            </button>
          );
        })}
      </div>

      {/* Quick Scripture Navigation widget in sidebar */}
      <div className="mt-auto pt-6 border-t border-[#252834]">
        <div className="p-3 rounded-xl bg-[#191C24] border border-[#2B2E3A]">
          <span className="text-[10px] uppercase font-semibold text-[#8C877D] tracking-wider block mb-1">
            Authoritative Scripture
          </span>
          <p className="text-xs text-[#A9A397] leading-relaxed">
            Read reverently. Never modified or generated by AI models.
          </p>
        </div>
      </div>
    </aside>
  );
};
